### ISSUE TITLE
Add XML pipeline

### ISSUE THREAD

**Issue by rofe** [adobe/hypermedia-pipeline#106]
Like the JSON pipeline, but assume that the output is a XML document.

Use case: implement a sitemap.xml

**Comment by trieloff** [comment]
Just like the JSON pipeline, I don't think you would have an `xml.htl`, but instead write a straight `xml.js` with a main function.

**Comment by rofe** [comment]
> Just like the JSON pipeline, I don't think you would have an `xml.htl`, but instead write a straight `xml.js` with a main function.
We should support both cases, I guess.

**Comment by trieloff** [comment]
We do. The `xml.htl` would get compiled into `xml.js` anyway. `xml.htl` just sets the response body directly, so the additional validation step we discussed in #107 would be extra necessary then.
