### ISSUE TITLE
Provide tap function in the pipeline builder to enable in-progress inspection

### ISSUE THREAD

**Issue by trieloff** [adobe/hypermedia-pipeline#14]
Calling `pipe.pre(mystep).tap(myfn)`

should ensure that `myfn` will be called before `mystep` is executed by the pipeline, but that the return value of `myfn` will not enter the pipeline.

This allows setting `myfn` as an observer to `mystep`, which can ease debugging and inspection.

**Comment by tripodsan** [comment]
why before? the `taps` should be sequetially in the way they are defined.

```
pipe
.tap(t1)
.pre(p1)
.tap(t2)
.once(o)
....
```
will call t1 -> p1 -> t2 -> o;

OTOH, it is not clear to me what the benefit of tap is. if for debugging with a debugger, then it is easier to set the breakpoint accordingly. if debugging with loggers, then it should be possible to define the loglevels more cleverly.

i.e. I don't think that someone writes a special tap function, just to debug his pre function.

**Comment by trieloff** [comment]
The use case I was thinking of was writing an integration test for the pipeline (see adobe/helix-cli#18) – you'd want to be able to get a full dump of the current payload, so your tap would just write the current payload to disk, allowing you to copy it into your test directory.

**Comment by tripodsan** [comment]
but wouldn't this rather by a generic testing/tapping capability of the pipeline itself? 
but it might be a good modular approach to this.

**Comment by trieloff** [comment]
Not needed, we have better debugging options now.

**Comment by trieloff** [comment]
We need taps (among others) for type validation.
