### ISSUE TITLE
Add JSON pipeline

### ISSUE THREAD

**Issue by trieloff** [adobe/hypermedia-pipeline#16]
Like the HTML pipeline, but assume that the output is a JSON document

**Comment by tripodsan** [comment]
who would consume this json ?

**Comment by tripodsan** [comment]
I think modern SPAs don't want single resource JSONs. they want to dynamically load data with graphql like requests or respective backends. 

/cc @kptdobe

**Comment by kptdobe** [comment]
What I would do right now is provide the simple pipeline from @trieloff and make it extensible (i.e. you can override json.pipe.js). Then I would give that to several integrators to see how far they can go with it and see if graphql really makes sense to start with.
With the selectors and the pre.js files, you can already do a lot in terms of splitting your resources.

We should also get feedback from the AEM SPA team (@martinischeery @gabrielwalt @pfauchere)

**Comment by tripodsan** [comment]
I agree. this will be addressed with the changes in the HTL plugin  (https://github.com/adobe/parcel-plugin-htl/issues/22) and hlx build (https://github.com/adobe/helix-cli/issues/70)

**Comment by trieloff** [comment]
> Why do I need to had an HTL template to render JSON ?

Right now, HTL is our only working templating language. This is clearly not sufficient and not enough. I believe that we should support any templating language that is able to produce a pure JS function (and that includes hand-written JS functions)

The changes @tripodsan mentioned here 
https://github.com/adobe/hypermedia-pipeline/issues/16#issuecomment-412018449 will make this possible.

> While adding json.pipe.js feels natural, it does the same thing than the HTML pipe thus why would I need it ?

You should not need it, because JSON is important enough so that we support it out of the box. In the end, the HTML and JSON pipeline will have many differences including:

- `Content-Type` header
- handling of include logic: nobody wants to write `<esi:include>` in their JSON, so we need to find a way to express inclusions in JSON and transform them into ESI in the pipeline
- the HTML pipeline will pull `<meta http-equiv>` out of the body and turn it into proper headers. The JSON pipeline won't

**Comment by tripodsan** [comment]
I quickly looked into this, then problem is how to generate/select the json action in general:

- we don't want to offer .json feed for all pages, I guess
- if we don't have a _json.js_ openwhisk action, how does the edge know who to call?
- since json is so "important", maybe we support serving json for each action in general. i.e. every html.js script can also deliver the respective json. and you can use a `json.pre.js` if you want to alter it.

**Comment by pfauchere** [comment]
Regarding the need of modern SPAs, from my understanding, it is mostly about the freedom of aggregating multiple sources than using GraphQL or getting rid of a static data representation. Of course, a solution like GraphQL provides the API consumer with a good amount of flexibility and autonomy and is, therefore, a favored option. It is even truer when considering a headless CMS.

**Comment by trieloff** [comment]
@tripodsan 
> then problem is how to generate/select the json action in general

I'd say we provide a default JSON action and applications will use the selector infrastructure to pick the correct JSON representation.

The default JSON representation could range from extremely chatty

```javascript
module.exports.main = async function main(payload) {
  return {response: Object.assign({}, payload)};
}
```

to extremely terse:

```javascript
module.exports.main = async function main(payload) {
  return {response: Object.assign({}, payload)};
}
```

I think we have some time to iterate over the default representation, so that's fine.

 > we don't want to offer .json feed for all pages, I guess

See above: I think we should.

> if we don't have a `json.js` openwhisk action, how does the edge know who to call?

If you call a non-existent resource, you will get an error 404. Fastly will try to call the `json` action, and understand that there is no JSON action and turn this into a 404.

> since json is so "important", maybe we support serving json for each action in general. i.e. every `html.js` script can also deliver the respective json. and you can use a json.pre.js if you want to alter it.

I think this could be a nice implementation of the default JSON pipeline: just fetch the corresponding HTML, escape everything, and return it.

**Comment by trieloff** [comment]
@pfauchere GraphQL would fit into this picture in two ways:

1. a `graphql.json` default pipeline that implements a GraphQL server. Clients would be able to POST generic GraphQL queries and they would be evaluated against the `payload` 
2. GraphQL as a "templating language" would allow you to create a `myquery_json.graphql` file, which can be requested with a GET request and yield the correct result

Option 2 would be 100% cachable, caching option 1 will be harder.

**Comment by tripodsan** [comment]
> I think this could be a nice implementation of the default JSON pipeline: just fetch the corresponding HTML, escape everything, and return it.

What I thought is, that the default `html` action can also render `json` if requested (via accept header). a potential `json.pre.js` would also be included into the `html.js`.

> 2. GraphQL as a "templating language" would allow you to create a myquery_json.graphql file, which can be requested with a GET request and yield the correct result

+1 I'm a fan of stored queries :-)
