### ISSUE TITLE
[pre.js] Strainconfig missing in the payload

### ISSUE THREAD

**Issue by kptdobe** [adobe/hypermedia-pipeline#17]
To gather the metadata, a `pre.js` needs the strainconfig to know the content and code urls to be able to request things on its own.

@trieloff Your sample has an hardcoded version of that url, what if the content needs to be requested locally ? See https://github.com/adobe/parcel-plugin-htl/blob/21167e6168166f6f74c79a7389f03a842c3adbc3/test/example/alex_html.pre.js#L18

**Comment by trieloff** [comment]
This should be passed in through `secrets`. In `fetch` we use it to pass the `REPO_ROOT_URL`

**Comment by trieloff** [comment]
See https://github.com/adobe/hypermedia-pipeline/blob/master/src/html/fetch-markdown.js#L37

**Comment by kptdobe** [comment]
I need REPO_API_ROOT... I need to add it to Petridish. See https://github.com/adobe/petridish/issues/18
