### ISSUE TITLE
Replace yaml with js-yaml

### ISSUE THREAD

**Issue by trieloff** [adobe/hypermedia-pipeline#18]
Helix-CLI has 18 different dependencies to `js-yaml` and only one to `yaml`. This one.

**Comment by tripodsan** [comment]
please elaborate :-) where/what ?

**Comment by trieloff** [comment]
`js-yaml` and `yaml` are doing the same thing. Most of our code base is using `js-yaml` (just search for it in helix-cli's `package-lock.json`, and hypermedia-pipeline is the only place where the `yaml`library is used.
