### ISSUE TITLE
Provide REPO_RAW_ROOT and REPO_API_ROOT to `pre.js` via secrets

### ISSUE THREAD

**Issue by kptdobe** [adobe/hypermedia-pipeline#20]
To be able to make extra requests and enhance the payload, the `pre.js` might need the raw and the api root urls. This is currently achieved in Petridish with the REPO_RAW_ROOT and REPO_API_ROOT. The same should be done in the pipeline.

**Comment by tripodsan** [comment]
can't the API url be computed from the RAW root, or the other way around?

**Comment by trieloff** [comment]
@kptdobe not necessarily: you can run `hlx deploy --default REPO_API_ROOT https://www.whatever.com` and it should end up in `secrets`

**Comment by kptdobe** [comment]
Oh yeah... `I used hlx deploy --default REPO_API_ROOT https://api.github.com/ --default REPO_RAW_ROOT https://raw.githubusercontent.com/...`, we now have the nav and the committers!
