### ISSUE TITLE
Request object from payload is not complete

### ISSUE THREAD

**Issue by kptdobe** [adobe/hypermedia-pipeline#32]
Step to reproduce:
1. run `hlx init test`
2. edit `src/html.pre.js` and add `console.log(payload.request);` to the `pre` function
3. run  `hlx up`
4. open `http://localhost:3000/index.html`
5. check the logs:

```
   { headers: undefined,
     params: 
      { owner: 'helix',
        repo: 'content',
        ref: 'master',
        path: 'index.md' },
     method: undefined }
```
`headers` and `method` are undefined but also missing the request details like uri, server...

**Comment by kptdobe** [comment]
The `request` object is important in the `pre` function if you want to make other calls to the server.

**Comment by tripodsan** [comment]
nevermind....when invoking the action via the openwhisk tool, it doesn't set the __ow_* params.
