### ISSUE TITLE
Proposed: We fail fast here

### ISSUE THREAD

**Issue by simonwex** [adobe/hypermedia-pipeline#38]
I think receiving an empty response object down the stack is likely to be confusing and result in more difficult debugging if this fails. My suggestion would be to bubble the failure up to comprehensively fail.

https://github.com/adobe/hypermedia-pipeline/blob/6b40a835d21bd59ce094432d5a3b603cd99c866f/src/defaults/default.js#L56

Thoughts?

(https://en.wikipedia.org/wiki/Fail-fast what I'm referencing in title)

**Comment by tripodsan** [comment]
the `req` here is not the request from openwhisk but the external request that was sent to the browser. the `req` can be empty, but maybe the parse error should fail indeed.

**Comment by tripodsan** [comment]
we should still fail, if there is a parse error....

**Comment by tripodsan** [comment]
fixed with #46
