### ISSUE TITLE
Rename 'pre' to be less confusing with the `pre.js`

### ISSUE THREAD

**Issue by tripodsan** [adobe/hypermedia-pipeline#41]
The pipeline execution uses 3 main methods: `pre -> once -> after`

See https://github.com/adobe/hypermedia-pipeline/blob/master/src/defaults/html.pipe.js#L33-L45

The `pre` function name is confusing because of the `pre.js` file name.

Suggestion is to replace by: `before -> once -> after`

**Comment by trieloff** [comment]
+1
