### ISSUE TITLE
Layout Machine

### ISSUE THREAD

**Issue by trieloff** [adobe/hypermedia-pipeline#50]
@simonwex built a state machine for inferring the content type of a section based on the sequence of children of the section. 

I think this could be a great complement to the simple frequency-based approach taken in #47 

I've been looking for a way to express the same pattern matching logic with less code and stumbled upon https://github.com/mrijk/speculaas (documentation here https://mrijk.github.io/speculaas/api-reference.html), which is a Javascript implementation of Clojure Spec (https://clojure.org/guides/spec#_sequences)

It would allow us to specify sequences in a syntax like this:

```javascript
// read as regex: heading? image image image+ i.e. one optional heading and at least three images
s.cat(s.question('heading'), 'image', 'image', s.plus('image'));

// one optional heading and then paragraphs or lists
s.cat(s.question('heading'), s.plus(s.alt('paragraph', 'list')));
```

@kptdobe do you think this would be useful?

**Comment by kptdobe** [comment]
Yes, I think it is worth trying this (even though the syntax is not fully obvious on the first look)

**Comment by trieloff** [comment]
I think we can turn this into a more obvious syntax, without having to rely on that library, simply by using regular expressions.
