### ISSUE TITLE
Debug for the `action` object

### ISSUE THREAD

**Issue by kptdobe** [adobe/hypermedia-pipeline#51]
With https://github.com/adobe/hypermedia-pipeline/issues/19, we introduce a console log of the payload. It is still hard to know what is in the `action` object. This one contains:
- `logger`: which is useless to output
- `secrets`: which in theory should not be output. In dev mode (Petridish), knowing what's in the secrets is still required and useful but could be achieved with the debugger in the pre.js file.
- `request`: needed when doing more advanced stuff

In general, interacting with the `action` object is needed for advanced operations, thus I think using the debugger would be enough. Especially now we could debug the pre.js directly.

**Comment by trieloff** [comment]
In addition, the `action` object is pretty static so that the documentation in #62 should suffice.

Closing this for now.
