### ISSUE TITLE
Implement documented Global Scope

### ISSUE THREAD

**Issue by trieloff** [adobe/hypermedia-pipeline#7]
As pointed out in adobe/project-helix#237, we need to document the properties of the payload object in a structured fashion.

@tripodsan I've thought that we could maybe write JSON Schemas for the payload object and have a validation step in our pipelines that runs in development-mode, but is disabled in production. WDYT?

**Comment by kptdobe** [comment]
Following up @tripodsan's proposal in https://github.com/adobe/petridish/issues/46, payload could look like this:
```
{
    request: { 
        headers: { ... },
        url: '/index.html',
        selector: '',
        path: '/index',
        params: {
            debug: true
        },
        method: 'GET'
    },
    resource: { 
        body: '/* md content */',
        mdast: { ... },
        meta: { ... },
        title: 'AdobeIO APIs',
        intro: 'This is the welcome page.',
        htast: { ... },
        html: 'generated html',
        children: [ ... ] 
    }
}
```
(content of the resource object is out-of-score here and deserved its own issue).
The request object being the original request. 
The `pre` function would receive another optional parameter (named `action`) which would look like this:
```
{
    request: { 
        headers: { ... },
        params: {
            owner: 'helix',
            repo: 'content',
            ref: 'master',
            path: '/index.md',
            method: 'GET' 
        },
    },
    logger: ...,
    secrets: {
         REPO_RAW_ROOT: '...',
         ...
    },
}
```
and whole give access to the action call request which might be useful in certain cases.

**Comment by trieloff** [comment]
+1 to this proposal, which is also what's documented here: https://github.com/adobe/hypermedia-pipeline#anatomy-of-the-payload

**Comment by trieloff** [comment]
With one exception: I'd keep `secrets` out of `payload` because people will `console.log(payload)` and accidentally spill `secrets` that should never be logged.

**Comment by tripodsan** [comment]
> With one exception: I'd keep secrets out of payload because people will console.log(payload) and accidentally spill secrets that should never be logged.

yes. this is in the 2nd argument: `action` as mentioned above.

**Comment by tripodsan** [comment]
I don't think we need to change anything in pipeline, except maybe renaming some vars?

**Comment by trieloff** [comment]
> What about having the secrets as non-enumerable property?

+1

**Comment by trieloff** [comment]
I also spoke with @sjvs today and he suggested that we could create a lgtm.com query to detect cases where there is a data flow from `action` into either `console` whatever the `return` value is.

**Comment by tripodsan** [comment]
After thinking about this some more, I propose to move all _wrapping_ and _adapting_ logic to this pipeline. there is already the `adaptOWRequest()`, but this doesn't do much yet. so maybe we can move the changes from https://github.com/adobe/helix-cli/pull/141 to here; and adjust the pipeline, that it either can manipulate the action, or have a dedicated `init()` and `final()` step that transform the ow-signature (params) to the pipeline signature (payload, action); and back to the ow response.

this would encapsulate all the header/param/secret magic in our (this) module, away from the generated html.js, and simplify the html.js to something like:

```
module.exports.main = function main(params) {
  const pre = require('pre.js');
  cont pipe = require('hypermedia/default');
  return pipe.pre(thisPre).once(compliledScriptMain)(params);
}
```

**Comment by trieloff** [comment]
Given that the debugging the generated HTML is a major pain (and debugging steps in the pipeline only a relative pain), that seems to be a good idea.

**Comment by kptdobe** [comment]
While this could be a good improvement, I think it has nothing to do in here: changing the payload does not require this change.

**Comment by tripodsan** [comment]
> I think it has nothing to do in here: changing the payload does not require this change.

well, It's not only the payload but also the action; so the entire "signature".
