### ISSUE TITLE
HTML Navigation/TOC Pipeline and Markdown and JSON Format

### ISSUE THREAD

**Issue by trieloff** [adobe/hypermedia-pipeline#71]
Rendering navigation elements is a pretty common use case that can be handled by creating a `TOC.md`, `SUMMARY.md` or `SITEMAP.md` that contains lists of links to be shown in a navigation.

I suggest we define a Markdown subset that is best suited for Navigations and is able to express patterns commonly found in site navigations.

We then provide a separate HTML+JSON Pipeline for navigation that will parse the Markdown, and represent the navigation in a compact JSON format, so that custom navigations can be built easily.

**Comment by kptdobe** [comment]
In the 2 projects I built, I used the same pattern: 

* have a ([summary_html.htl](https://github.com/adobe/project-helix.io/blob/master/src/summary_html.htl), [summary_html.pre.js](https://github.com/adobe/project-helix.io/blob/master/src/summary_html.pre.js))
* do the include with ESI (https://github.com/adobe/project-helix.io/blob/master/src/html.htl#L42)
* use a the Markdown representing the nav is a list (https://github.com/adobe/project-helix.io/blob/master/SUMMARY.md).

This works pretty well.

Is the goal here to add something similar directly included in the pipeline that could use ootb ?

**Comment by trieloff** [comment]
Yes, that's the goal.

For simple navigations, you would create the Markdown, do the ESI and roll with the defaults. 

The navigation pipeline would have some differences from the standard HTML pipeline, e.g.

- do detect internal and external links
- don't split in sections

Ultimately, I want to be able to support complex structures like on adobe.com

<img width="817" alt="screen shot 2018-10-12 at 16 10 36" src="https://user-images.githubusercontent.com/39613/46874399-5d629680-ce39-11e8-82a0-e01356f4ae49.png">

In that screenshot alone, you have:

- multiple levels: "Creativity & Design" leading to "Creative Cloud plans"
- link titles and descriptions: "What is Creative Cloud" & Creative apps and services for everyone"
- multiple link types: "view all plans & pricing" is a higher priority link
- multiple columns (or are they sub-lists)?: "Creative Cloud Plans" vs. "Featured products"

And then scroll down for some extra craziness:

<img width="1286" alt="screen shot 2018-10-12 at 16 16 38" src="https://user-images.githubusercontent.com/39613/46874766-348ed100-ce3a-11e8-8fe7-6cd0727fee3c.png">

- text links vs. image links vs. text & image links
- columns and columns within columns

**Comment by trieloff** [comment]
Obsolete with #112
